import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Nav from "./nav";
import { Toaster } from "@/components/ui/toaster";
import Footer from "./footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    inter.className,
                    "disable-scroll-x flex min-h-screen w-screen flex-col bg-primary",
                )}
            >
                <Nav />
                <main className="flex-grow bg-background">{children}</main>
                <Footer />
                <Toaster />
            </body>
        </html>
    );
}
